include_defs('//lib/maven.defs')

maven_jar(
  name = 'httpcore',
  id = 'org.apache.httpcomponents:httpcore:4.3.2',
  sha1 = '31fbbff1ddbf98f3aa7377c94d33b0447c646b6e',
  license = 'Apache2.0',
)

maven_jar(
  name = 'httpclient',
  id = 'org.apache.httpcomponents:httpclient:4.3.2',
  sha1 = '10a45d03873baa34436ae54548d9f1140d4bb68a',
  license = 'Apache2.0',
)
